# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[default]
auto_detect_solc = false
fuzz_runs = 256
libs = ["lib"]
gas_reports = ["*"]
optimizer = false
out = "out"
solc = "0.6.12"
src = "src"
test = "test"
verbosity = 2
